"""Database creation_1

Revision ID: 2b813cc61b51
Revises: 
Create Date: 2023-05-25 16:25:18.124226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b813cc61b51'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Cluster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Cluster_id'), 'Cluster', ['id'], unique=False)
    op.create_table('Role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_Role_id'), 'Role', ['id'], unique=False)
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('idRole', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('passwordHash', sa.String(), nullable=False),
    sa.Column('idCluster', sa.Integer(), nullable=True),
    sa.Column('markingDeletion', sa.Boolean(), nullable=False),
    sa.Column('createData', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['idCluster'], ['Cluster.id'], ),
    sa.ForeignKeyConstraint(['idRole'], ['Role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_User_id'), 'User', ['id'], unique=False)
    op.create_table('Project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('idAutor', sa.Integer(), nullable=True),
    sa.Column('createData', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['idAutor'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Project_id'), 'Project', ['id'], unique=False)
    op.create_index(op.f('ix_Project_idAutor'), 'Project', ['idAutor'], unique=False)
    op.create_table('Task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('createData', sa.TIMESTAMP(), nullable=False),
    sa.Column('idProject', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idProject'], ['Project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Task_id'), 'Task', ['id'], unique=False)
    op.create_index(op.f('ix_Task_idProject'), 'Task', ['idProject'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Task_idProject'), table_name='Task')
    op.drop_index(op.f('ix_Task_id'), table_name='Task')
    op.drop_table('Task')
    op.drop_index(op.f('ix_Project_idAutor'), table_name='Project')
    op.drop_index(op.f('ix_Project_id'), table_name='Project')
    op.drop_table('Project')
    op.drop_index(op.f('ix_User_id'), table_name='User')
    op.drop_table('User')
    op.drop_index(op.f('ix_Role_id'), table_name='Role')
    op.drop_table('Role')
    op.drop_index(op.f('ix_Cluster_id'), table_name='Cluster')
    op.drop_table('Cluster')
    # ### end Alembic commands ###
